### ISSUE TITLE
Add the pod!

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/pod-4.1.1-portfolio#15]
Currently, then repository has members of the MLH team on it, but you should replace them with members of the pod.

You can update information in `_data/fellows.yml`

You should work on:
- [ ] Replacing the images
- [ ] Update the names and locations of each fellow
- [ ] Update the pod number inside of `_config.yml`

**Comment by Swatilekha-Roy** [comment]
I am really interested in this issue, would love to try my hands on it! Could you please assign it to me, if that's okay? Thanks in advance!

**Comment by khattakdev** [comment]
> I am really interested in this issue, would love to try my hands on it! Could you please assign it to me, if that's okay? Thanks in advance! I am also more than happy to work on it with someone else.

Awesome, you can take the required information from this [discussion](https://github.com/orgs/MLH-Fellowship/teams/pod-4-1-1/discussions/1)
