### ISSUE TITLE
[Bug] Title "Pod 4.1.X" to "Pod 4.1.1"

### ISSUE THREAD

**Issue by gavishpoddar** [MLH-Fellowship/pod-4.1.1-portfolio#23]
Hi,
There is an issue on a page [title](https://github.com/MLH-Fellowship/pod-4.1.1-portfolio/blob/main/_config.yml) that sets the title to Pod `4.1.X`. It would be better if we can change it to `Pod 4.1.1` or `Pod 4.1.1 :  Arch Eagle`

**Comment by khattakdev** [comment]
@gavishpoddar This is already being managed by @Devansh3712 here https://github.com/MLH-Fellowship/pod-4.1.1-portfolio/pull/18

**Comment by gavishpoddar** [comment]
I didn't saw that. Notes taken :) 
Thanks @khattakdev
